create schema if not exists catalogue;
create table catalogue.t_guitar(
    id integer generated by default as identity primary key  ,
    c_manufacturer varchar(50) not null ,
    c_model varchar(50) not null ,
    c_price integer not null ,
    c_description varchar(1000)
);